### ISSUE TITLE
Overwriting files of duplicated gene hits

### ISSUE THREAD

**Issue by LindertBenedictus** [boasvdp/extract_genes_ABRicate#1]
Hi Boas,

Great script does exactly what it should. I noticed two things will using the script.

Readme: The script file name is an all lowercase letters "extract_genes_abricate.py", while in the example command line you use "extract_genes_ABRicate.py". 

Overwriting files
I had a duplicated gene in a genome and abricate therefore had two hits with the same genome/file name en gene name. For the output of your script you use the genome_gene_name format and in the case of duplicated genes I think this means the files are overwritten because the file names are the same.

Best,
Lindert

**Comment by boasvdp** [comment]
Hi Lindert,

Thanks! Happy the script is useful. 

I have edited the README and have fixed the issue with multiple of the same gene in the same strain. The script now goes through the ABRicate output file and appends `_2`, `_3` etc when multiple of the same gene are found. This is also printed to the terminal (STDERR). The test cases I have included seem to be working properly now. Can you check whether these work alright for you too now?

**Comment by LindertBenedictus** [comment]
That's quick. Yes it worked, it added a suffix to the output file and the message on the terminal also worked.
Thanks.
